# Generated by Django 4.1.2 on 2023-02-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_sport_team_teamtype_usertype_profile_battinghand_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="UserType",
        ),
        migrations.DeleteModel(
            name="UserType",
        ),
        migrations.AddField(
            model_name="profile",
            name="UserType",
            field=models.CharField(
                choices=[
                    ("P", "Parent"),
                    ("C", "Coach"),
                    ("PL", "Player"),
                    ("PC", "Parentcoach"),
                ],
                default="PL",
                max_length=2000,
            ),
        ),
    ]
