# Generated by Django 4.1.2 on 2023-02-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_secondphone_team_secondaryphone_team_teamlogo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="PrimaryEmail",
            field=models.EmailField(max_length=254),
        ),
    ]
