# Generated by Django 4.1.2 on 2023-02-12 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_team_primaryemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamWebsite",
            fields=[
                ("TeamWebsiteID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "HeaderImage",
                    models.ImageField(
                        default="default.jpg", upload_to="teamsite_images"
                    ),
                ),
                ("SiteTitle", models.CharField(max_length=100)),
                ("BackgroundColor", models.CharField(max_length=100)),
                ("MissionStatement", models.TextField()),
                ("ShowRoster", models.BooleanField(default=False)),
                ("ShowCoaches", models.BooleanField(default=False)),
                ("ShowPlayerMedia", models.BooleanField(default=False)),
                ("ShowGamesAndStats", models.BooleanField(default=False)),
                (
                    "TeamName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamWebsiteExternalLink",
            fields=[
                ("LinkID", models.AutoField(primary_key=True, serialize=False)),
                ("LinkName", models.CharField(max_length=1000, null=True)),
                ("Url", models.CharField(max_length=1000, null=True)),
                (
                    "SiteID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.teamwebsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamDocument",
            fields=[
                ("TeamDocumentID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Document",
                    models.FileField(default="default.jpg", upload_to="team_files"),
                ),
                ("ShowOnPublicWebsite", models.BooleanField(default=False)),
                ("ShowOnInternalWebsite", models.BooleanField(default=False)),
                (
                    "SiteID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.teamwebsite",
                    ),
                ),
                (
                    "TeamName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.team"
                    ),
                ),
            ],
        ),
    ]
