# Generated by Django 4.1.2 on 2023-02-12 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_sitestyle_remove_teamwebsite_backgroundcolor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamwebsite",
            name="SiteTheme",
        ),
        migrations.CreateModel(
            name="TeamStyle",
            fields=[
                ("TeamStyleID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "SiteTheme",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SiteTheme",
                        to="users.sitestyle",
                    ),
                ),
            ],
        ),
    ]
