# Generated by Django 4.1.2 on 2023-02-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_teamwebsite_sitetheme_teamstyle"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamwebsite",
            name="IsPublicSite",
            field=models.BooleanField(default=False),
        ),
    ]
