# Generated by Django 4.1.2 on 2023-02-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_teamwebsite_ispublicsite"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamwebsiteexternallink",
            name="ShowOnInternalWebsite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teamwebsiteexternallink",
            name="ShowOnPublicWebsite",
            field=models.BooleanField(default=False),
        ),
    ]
