# Generated by Django 4.1.2 on 2023-02-14 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_teamwebsiteexternallink_showoninternalwebsite_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamdocument",
            name="TeamName",
        ),
    ]
