# Generated by Django 4.1.2 on 2023-02-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_teamdocument_teamname"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamdocument",
            name="FileName",
            field=models.CharField(default="", max_length=100),
        ),
    ]
