# Generated by Django 4.1.2 on 2023-02-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_teamdocument_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamwebsite",
            name="SiteStyleOption",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("cerulean", "Cerulean"),
                    ("cosmo", "Cosmo"),
                    ("cyborg", "Cyborg"),
                    ("darkly", "Darkly"),
                    ("flatly", "Flatly"),
                    ("journal", "Journal"),
                    ("litera", "Litera"),
                    ("lumen", "Lumen"),
                    ("lux", "Lux"),
                    ("materia", "Materia"),
                    ("minty", "Minty"),
                    ("morph", "Morph"),
                    ("pulse", "Pulse"),
                    ("quartz", "Quartz"),
                    ("sandstone", "Sandstone"),
                    ("simplex", "Simplex"),
                    ("sketchy", "Sketchy"),
                    ("slate", "Slate"),
                    ("solar", "Solar"),
                    ("spacelab", "Spacelab"),
                    ("superhero", "Superhero"),
                    ("united", "United"),
                    ("vapor", "Vapor"),
                    ("yeti", "Yeti"),
                    ("zephyr", "Zephyr"),
                ],
                default="default",
                max_length=200,
                null=True,
            ),
        ),
    ]
