# Generated by Django 4.1.2 on 2023-02-15 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_teamwebsite_sitestyleoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamroster",
            name="FullName",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.CreateModel(
            name="TeamMedia",
            fields=[
                ("TeamMediaID", models.AutoField(primary_key=True, serialize=False)),
                ("MediaTitle", models.CharField(max_length=1000)),
                ("MediaDescription", models.TextField(max_length=5000)),
                ("MediaFile", models.FileField(upload_to="team_media")),
                (
                    "MediaType",
                    models.CharField(
                        choices=[("Image", "Image"), ("Video", "Video")],
                        default="Image",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "SiteID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.teamwebsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerMedia",
            fields=[
                ("PlayerMediaID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "SelectedPlayer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.teamroster",
                    ),
                ),
                (
                    "SelectedTeam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.team"
                    ),
                ),
                (
                    "TeamMediaItem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.teammedia",
                    ),
                ),
            ],
        ),
    ]
