# Generated by Django 4.1.2 on 2023-02-17 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0018_remove_teamroster_activemember_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamroster",
            name="ActiveMember",
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("TeamMemberID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "MemberType",
                    models.CharField(
                        choices=[("PARENT", "Parent"), ("COACH", "Coach")],
                        default="PARENT",
                        max_length=2000,
                    ),
                ),
                (
                    "AssignedTeam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.team"
                    ),
                ),
                (
                    "MemberUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
