# Generated by Django 4.1.2 on 2023-02-17 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0020_teamfaninviterequest_membertype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamcoach",
            name="Role",
        ),
        migrations.AddField(
            model_name="team",
            name="CurrentSeason",
            field=models.CharField(
                choices=[
                    ("FALL", "Fall"),
                    ("SPRING", "Spring"),
                    ("SUMMER", "Summer"),
                    ("WINTER", "Winter"),
                ],
                default="FALL",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="CurrentYear",
            field=models.CharField(default=2023, max_length=4),
        ),
        migrations.AddField(
            model_name="team",
            name="DateCreated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="teamcoach",
            name="CoachTitle",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="teamcoach",
            name="Coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
