# Generated by Django 4.1.2 on 2023-02-19 02:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0022_teammember_teamowner"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequestQueue",
            fields=[
                (
                    "DateTimeCreated",
                    models.DateField(auto_created=True, default=datetime.datetime.now),
                ),
                (
                    "AccessRequestQueueID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "MemberType",
                    models.CharField(
                        choices=[("PARENT", "Parent"), ("COACH", "Coach")],
                        default="PARENT",
                        max_length=2000,
                    ),
                ),
                ("DateTimeModified", models.DateField(default=datetime.datetime.now)),
                (
                    "RequestStatus",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="OPEN",
                        max_length=2000,
                    ),
                ),
                (
                    "Approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Approve_User",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Requestor_User",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "TeamRequested",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Team_Requested",
                        to="users.team",
                    ),
                ),
            ],
        ),
    ]
